function [m] = TransX(a)
%TransX returns homogeneous transformation matrix moving along with x axis with the disntance of a
m = [1, 0, 0, a;...
     0, 1, 0, 0;...
     0, 0, 1, 0; ...
     0, 0, 0, 1];
end