function [m] = RotX(q)
%RotX returns homogeneous transformation matrix around x axis with the angle of q
m = [1, 0, 0, 0; ...
    0, cos(q), -sin(q), 0;...
    0, sin(q), cos(q), 0; ...
    0, 0, 0, 1];
end

