function [m] = RotY(q)
%RotY returns homogeneous transformation matrix around y axis with the angle of q
m = [cos(q), 0, sin(q), 0; ...
    0, 1, 0, 0;...
    -sin(q), 0, cos(q), 0; ...
    0, 0, 0, 1];
end