function [m] = TransY(a)
%TransY returns homogeneous transformation matrix moving along with y axis with the disntance of a
m = [1, 0, 0, 0;...
     0, 1, 0, a;...
     0, 0, 1, 0; ...
     0, 0, 0, 1];
end